name: Build ubootmod-standard-Version Redmi AX6000

on:
  workflow_dispatch:  # 手动触发（推荐）

jobs:
  build:
    runs-on: ubuntu-22.04  # OpenWrt 推荐版本，稳定性高
    steps:
      - name: 检出最新代码（padavanonly/immortalwrt-mt798x-6.6）
        uses: actions/checkout@v6.0.2
        with:
          repository: padavanonly/immortalwrt-mt798x-6.6
          ref: openwrt-24.10-6.6  # 当前活跃分支（内核 6.6）
          path: immortalwrt
          fetch-depth: 0

      - name: 安装编译环境依赖（官方 ImmortalWrt 脚本）
        run: |
          sudo apt-get update
          sudo bash -c "$(curl -fsSL https://build-scripts.immortalwrt.org/init_build_environment.sh)"

      - name: 缓存 dl/
        uses: actions/cache@v5.0.3
        id: cache-dl
        with:
          path: immortalwrt/dl
          key: ${{ runner.os }}-immortalwrt-dl-${{ hashFiles('immortalwrt/feeds.conf.default') }}-${{ hashFiles('immortalwrt/.config') }}
          restore-keys: ${{ runner.os }}-immortalwrt-dl-
          
      - name: 更新 feeds 并安装
        working-directory: immortalwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: 缓存 staging_dir/
        uses: actions/cache@v5.0.3
        id: cache-staging
        with:
          path: immortalwrt/staging_dir
          key: ${{ runner.os }}-immortalwrt-staging-${{ hashFiles('immortalwrt/feeds.conf.default') }}-${{ hashFiles('immortalwrt/.config') }}
          restore-keys: ${{ runner.os }}-immortalwrt-staging-

      - name: add ubootmod-standard pathch
        run: |
         tree ./
         cp target/linux/mediatek/dts/mt7986a-xiaomi-redmi-router-ax6000-ubootmod-standard.dts immortalwrt/target/linux/mediatek/dts/
         batch scripts/apply_multi_version_patches.sh
         cp defconfig/mt7986a-ax6000-ubootmod.config immortalwrt/.config


      - name: 加载 Redmi AX6000 U-Boot 版本配置（ubootmod）
        working-directory: immortalwrt
        run: |
          echo "CONFIG_CCACHE=y" >> .config
          make defconfig
          # 可选：查看最终配置（调试用）
          grep -E "TARGET|DEVICE|ubootmod" .config

      - name: 下载源码（加速后续编译）
        working-directory: immortalwrt
        run: |
          make download -j$(nproc) || true

      - name: 开始编译（U-Boot mod 固件）
        working-directory: immortalwrt
        run: |
          make -j$(nproc) V=s 2>&1 | tee image-build.log
        env:
          MAKEFLAGS: "-j$(nproc)"

      - name: 上传编译产物（U-Boot 版本固件）
        uses: actions/upload-artifact@v7.0.0
        with:
          name: ImmortalWrt-Redmi-AX6000-UbootMod-${{ github.run_number }}
          path: |
            immortalwrt/bin/targets/mediatek/filogic/*
          retention-days: 30

      - name: 清理缓存（可选，节省空间）
        if: always()
        working-directory: immortalwrt
        run: |
          rm -rf staging_dir/build_dir || true
